export const config = {
  Backgrounds: {
    default: 'blue50',
    blue60: 'blue60',
    blue70: 'blue70',
    green60: 'green60',
    green70: 'green70',
    grey40: 'grey40',
    grey70: 'grey70',
    grey80: 'grey80',
    red50: 'red50',
    red60: 'red60',
    red70: 'red70',
    yellow50: 'yellow50',
    yellow60: 'yellow60',
    yellow70: 'yellow70',
  },
  Ears: {
    default: 'default',
    'tilt-backward': 'tilt-backward',
    'tilt-forward': 'tilt-forward',
  },
  Eyes: {
    default: 'default',
    angry: 'angry',
    naughty: 'naughty',
    panda: 'panda',
    smart: 'smart',
    star: 'star',
  },
  Hair: {
    default: 'default',
    bang: 'bang',
    curls: 'curls',
    elegant: 'elegant',
    fancy: 'fancy',
    short: 'short',
  },
  Leg: {
    default: 'default',
    cookie: 'cookie',
    'bubble-tea': 'bubble-tea',
    'game-console': 'game-console',
    'tilt-backward': 'tilt-backward',
    'tilt-forward': 'tilt-forward',
  },
  Mouth: {
    default: 'default',
    astonished: 'astonished',
    eating: 'eating',
    laugh: 'laugh',
    tongue: 'tongue',
  },
  Neck: {
    default: 'default',
    'bend-backward': 'bend-backward',
    'bend-forward': 'bend-forward',
    thick: 'thick',
  },
  Accessories: {
    earings: 'earings',
    flower: 'flower',
    glasses: 'glasses',
    headphone: 'headphone',
  },
  Nose: {
    default: 'default',
  },
}

export const defaultSettingValues = {
  Backgrounds: 'blue50',
  Ears: 'default',
  Eyes: 'default',
  Hair: 'default',
  Leg: 'default',
  Mouth: 'default',
  Neck: 'default',
  Accessories: 'glasses',
  Nose: 'default',
}
